/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import cliente.Cliente;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 * Janela principal do chat.
 * @author rafaelpaiva
 */
public class ClienteGUI extends javax.swing.JFrame {
    /**
     * Creates new form ClienteGUI.
     */
    public ClienteGUI() {
	initComponents();
	new ConnectDialog(this,true).setVisible(true);
    }
    
    public void IniciarConexao(String ip, int porta, String nick) throws IOException, Exception {
	Cliente.Conectar(ip, porta, nick);
	System.out.println("Cliente criado.");
	Cliente.IniciarEscuta(chatArea.getStyledDocument(), nickArea, this);
	System.out.println("Escuta iniciada!");
	conButton.setText("Desconectar");
	stateLabel.setText("Conectado com: "+ip+". Nick: "+nick);
	EnableComponents();
    }
    
    private void EnableComponents () {
	msgTextField.setEnabled(true);
	sendMsgButton.setEnabled(true);
	chatArea.setEnabled(true);
	nickArea.setEnabled(true);
    }
    
    public void DisableComponents () {
	conButton.setText("Conectar");
	stateLabel.setText("Desconectado");
	msgTextField.setEnabled(false);
	sendMsgButton.setEnabled(false);
	chatArea.setEnabled(false);
	nickArea.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MensagemPainel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        msgTextField = new javax.swing.JTextField();
        sendMsgButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        nickArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        conButton = new javax.swing.JButton();
        stateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat do Cardoso, Mendes e Paiva");
        setBounds(new java.awt.Rectangle(0, 0, 10, 10));
        setMinimumSize(new java.awt.Dimension(450, 350));
        setPreferredSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        MensagemPainel.setPreferredSize(new java.awt.Dimension(148, 35));
        MensagemPainel.setLayout(new javax.swing.BoxLayout(MensagemPainel, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Mensagem: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(90, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(90, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 17));
        MensagemPainel.add(jLabel2);

        msgTextField.setEnabled(false);
        msgTextField.setMaximumSize(new java.awt.Dimension(2147483647, 27));
        msgTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msgTextFieldKeyPressed(evt);
            }
        });
        MensagemPainel.add(msgTextField);

        sendMsgButton.setText("Enviar");
        sendMsgButton.setEnabled(false);
        sendMsgButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendMessage(evt);
            }
        });
        MensagemPainel.add(sendMsgButton);

        getContentPane().add(MensagemPainel, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(80, 260));

        StyledDocument doc = chatArea.getStyledDocument();
        Style bold = doc.addStyle("nick", null);
        StyleConstants.setBold(bold, true);
        Style date = doc.addStyle("date", null);
        StyleConstants.setForeground(date, Color.BLUE);
        chatArea.setStyledDocument(doc);
        chatArea.setEditable(false);
        chatArea.setEnabled(false);
        jScrollPane1.setViewportView(chatArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 87));

        nickArea.setEditable(false);
        nickArea.setColumns(1);
        nickArea.setRows(10);
        nickArea.setTabSize(4);
        nickArea.setEnabled(false);
        jScrollPane2.setViewportView(nickArea);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        jPanel1.setPreferredSize(new java.awt.Dimension(457, 40));

        conButton.setText("Conectar");
        conButton.setFocusable(false);
        conButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        conButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        conButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conButtonMouseClicked(evt);
            }
        });

        stateLabel.setText("Desconectado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateLabel)
                .addGap(0, 258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conButtonMouseClicked
       try {
	    if (Cliente.IsConected()) { //Desconectar
		Cliente.Desconectar();
		DisableComponents();
	    } else { //Conectar
	        new ConnectDialog(this,true).setVisible(true);
	    }
	} catch (IOException ex) {
	    Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_conButtonMouseClicked

    private void SendMessage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendMessage
        try {
	    Cliente.Enviar(msgTextField.getText());
	    msgTextField.setText("");
	} catch (IOException ex) {
	    Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_SendMessage

    private void msgTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msgTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
	    SendMessage(null);
	}
    }//GEN-LAST:event_msgTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    @Override
	    public void run() {
		new ClienteGUI().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MensagemPainel;
    private javax.swing.JTextPane chatArea;
    private javax.swing.JButton conButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField msgTextField;
    private javax.swing.JTextArea nickArea;
    private javax.swing.JButton sendMsgButton;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables
}
